import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`theme\` ADD \`twitter\` text;`)
  await db.run(sql`ALTER TABLE \`theme\` ADD \`facebook\` text;`)
  await db.run(sql`ALTER TABLE \`theme\` ADD \`instagram\` text;`)
  await db.run(sql`ALTER TABLE \`theme\` ADD \`linkedin\` text;`)
  await db.run(sql`ALTER TABLE \`theme\` ADD \`github\` text;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_twitter\` text;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_facebook\` text;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_instagram\` text;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_linkedin\` text;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` ADD \`version_github\` text;`)
  await db.run(sql`ALTER TABLE \`settings\` DROP COLUMN \`twitter\`;`)
  await db.run(sql`ALTER TABLE \`settings\` DROP COLUMN \`facebook\`;`)
  await db.run(sql`ALTER TABLE \`settings\` DROP COLUMN \`instagram\`;`)
  await db.run(sql`ALTER TABLE \`settings\` DROP COLUMN \`linkedin\`;`)
  await db.run(sql`ALTER TABLE \`settings\` DROP COLUMN \`github\`;`)
  await db.run(sql`ALTER TABLE \`_settings_v\` DROP COLUMN \`version_twitter\`;`)
  await db.run(sql`ALTER TABLE \`_settings_v\` DROP COLUMN \`version_facebook\`;`)
  await db.run(sql`ALTER TABLE \`_settings_v\` DROP COLUMN \`version_instagram\`;`)
  await db.run(sql`ALTER TABLE \`_settings_v\` DROP COLUMN \`version_linkedin\`;`)
  await db.run(sql`ALTER TABLE \`_settings_v\` DROP COLUMN \`version_github\`;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`settings\` ADD \`twitter\` text;`)
  await db.run(sql`ALTER TABLE \`settings\` ADD \`facebook\` text;`)
  await db.run(sql`ALTER TABLE \`settings\` ADD \`instagram\` text;`)
  await db.run(sql`ALTER TABLE \`settings\` ADD \`linkedin\` text;`)
  await db.run(sql`ALTER TABLE \`settings\` ADD \`github\` text;`)
  await db.run(sql`ALTER TABLE \`_settings_v\` ADD \`version_twitter\` text;`)
  await db.run(sql`ALTER TABLE \`_settings_v\` ADD \`version_facebook\` text;`)
  await db.run(sql`ALTER TABLE \`_settings_v\` ADD \`version_instagram\` text;`)
  await db.run(sql`ALTER TABLE \`_settings_v\` ADD \`version_linkedin\` text;`)
  await db.run(sql`ALTER TABLE \`_settings_v\` ADD \`version_github\` text;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`twitter\`;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`facebook\`;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`instagram\`;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`linkedin\`;`)
  await db.run(sql`ALTER TABLE \`theme\` DROP COLUMN \`github\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_twitter\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_facebook\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_instagram\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_linkedin\`;`)
  await db.run(sql`ALTER TABLE \`_theme_v\` DROP COLUMN \`version_github\`;`)
}
