/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    posts: Post;
    categories: Category;
    portfolio: Portfolio;
    'portfolio-categories': PortfolioCategory;
    'faq-categories': FaqCategory;
    faqs: Faq;
    testimonials: Testimonial;
    'job-vacancies': JobVacancy;
    'quote-requests': QuoteRequest;
    media: Media;
    plugins: Plugin;
    blocks: Block;
    'audit-logs': AuditLog;
    'security-events': SecurityEvent;
    'chatbot-leads': ChatbotLead;
    'chatbot-events': ChatbotEvent;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    search: Search;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    'portfolio-categories': PortfolioCategoriesSelect<false> | PortfolioCategoriesSelect<true>;
    'faq-categories': FaqCategoriesSelect<false> | FaqCategoriesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'job-vacancies': JobVacanciesSelect<false> | JobVacanciesSelect<true>;
    'quote-requests': QuoteRequestsSelect<false> | QuoteRequestsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    plugins: PluginsSelect<false> | PluginsSelect<true>;
    blocks: BlocksSelect<false> | BlocksSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'security-events': SecurityEventsSelect<false> | SecurityEventsSelect<true>;
    'chatbot-leads': ChatbotLeadsSelect<false> | ChatbotLeadsSelect<true>;
    'chatbot-events': ChatbotEventsSelect<false> | ChatbotEventsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    navigation: Navigation;
    settings: Setting;
    theme: Theme;
    'chatbot-settings': ChatbotSetting;
    'language-settings': LanguageSetting;
    'performance-settings': PerformanceSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    'chatbot-settings': ChatbotSettingsSelect<false> | ChatbotSettingsSelect<true>;
    'language-settings': LanguageSettingsSelect<false> | LanguageSettingsSelect<true>;
    'performance-settings': PerformanceSettingsSelect<false> | PerformanceSettingsSelect<true>;
  };
  locale: 'en' | 'zh-hk' | 'zh-cn' | 'id';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username?: string;
    email: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Show the floating admin shortcut panel on the frontend when logged in.
   */
  showAdminMenu?: boolean | null;
  /**
   * Enable TOTP-based 2FA for this account.
   */
  twoFactorEnabled?: boolean | null;
  twoFactorSecret?: string | null;
  twoFactorBackupCodes?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  username?: string | null;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Use "home" for the root page.
   */
  slug: string;
  /**
   * Page content. For metadata shown in search results and SEO, use the SEO Meta Description field.
   */
  excerpt?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Visual drag-and-drop page builder. Activate the Layout Builder plugin in Plugins to use.
   */
  layoutBuilder?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Classic block editor — visible when Layout Builder has no blocks. Useful for simple pages.
   */
  layout?:
    | (
        | {
            heading?: string | null;
            subheading?: string | null;
            image?: (number | null) | Media;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            media?: (number | null) | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            heading?: string | null;
            body?: string | null;
            label?: string | null;
            url?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            cards?:
              | {
                  image?: (number | null) | Media;
                  heading: string;
                  body?: string | null;
                  label?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardsGrid';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  number: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            url: string;
            caption?: string | null;
            poster?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            form: number | Form;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formBlock';
          }
        | {
            message: string;
            type?: ('info' | 'success' | 'warning' | 'error') | null;
            dismissible?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner';
          }
        | {
            language?: ('typescript' | 'javascript' | 'bash' | 'json' | 'css' | 'html' | 'python' | 'sql') | null;
            code: string;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'code';
          }
      )[]
    | null;
  publishedAt?: string | null;
  status: 'draft' | 'published';
  /**
   * Frontend template that renders this page.
   */
  pageTemplate?:
    | (
        | 'about-us'
        | 'app-development-services'
        | 'article'
        | 'article-detail'
        | 'article-detail-(/article/[slug])'
        | 'article-item'
        | 'contact'
        | 'dynamic-(catch-all-—-handles-/slug-and-/parent/slug)'
        | 'faq'
        | 'get-involved'
        | 'get-involved-community'
        | 'home'
        | 'hr-recruitment'
        | 'insight'
        | 'it-consulting'
        | 'portfolio'
        | 'portfolio-detail'
        | 'portfolio-item'
        | 'product-development'
        | 'qa-testing-services'
        | 'web-development-services'
        | 'who-we-serve'
      )
    | null;
  /**
   * When checked, this page renders at the root URL (/). Only one page should be marked as Frontpage.
   */
  isFrontpage?: boolean | null;
  /**
   * When checked, this page's Layout Builder becomes the template for all portfolio detail pages (/portfolio/<slug>).
   */
  portfolioDetailTemplate?: boolean | null;
  /**
   * When checked, this page's Layout Builder becomes the template for all article detail pages (/article/<slug>).
   */
  articleDetailTemplate?: boolean | null;
  meta?: {
    /**
     * Recommended 50–60 characters
     */
    title?: string | null;
    /**
     * Recommended 150–160 characters
     */
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * Excludes this page from sitemap and sets noindex/nofollow
     */
    noIndex?: boolean | null;
    /**
     * Leave blank to auto-generate from page URL
     */
    canonical?: string | null;
    /**
     * Used for Facebook/LinkedIn sharing (defaults to Meta Title if blank)
     */
    ogTitle?: string | null;
    /**
     * Used for social sharing cards (defaults to Meta Description if blank)
     */
    ogDescription?: string | null;
  };
  seo?: {
    /**
     * One plain-English sentence describing this page for AI tools (ChatGPT, Perplexity, Claude)
     */
    llmsEntry?: string | null;
    /**
     * Semantic topic tags for AI crawlers and internal search
     */
    topics?:
      | {
          topic: string;
          id?: string | null;
        }[]
      | null;
    contentType?: ('landing' | 'article' | 'job' | 'portfolio' | 'faq') | null;
    /**
     * Brief description of intended reader, e.g. "CTOs at Series A startups"
     */
    targetAudience?: string | null;
  };
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            stepLabel: string;
            stepDescription?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepSeparator';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            scaleMin?: number | null;
            scaleMax?: number | null;
            minLabel?: string | null;
            maxLabel?: string | null;
            scoreWeight?: number | null;
            width?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'scale';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  scoring?: {
    enabled?: boolean | null;
    /**
     * Points awarded when all fields are filled in (pro-rated)
     */
    completenessWeight?: number | null;
    /**
     * Award extra points when a field matches a specific value
     */
    fieldWeights?:
      | {
          fieldName: string;
          matchValue: string;
          points?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-friendly identifier, e.g. "my-first-post"
   */
  slug: string;
  author?: (number | null) | User;
  categories?: (number | Category)[] | null;
  featuredImage?: (number | null) | Media;
  /**
   * A brief summary shown on article cards and grid listings (2–3 sentences).
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  status: 'draft' | 'published';
  /**
   * Mark this post as featured. The Article Feature block (in Collection mode) shows the featured post for the active category filter.
   */
  featured?: boolean | null;
  meta?: {
    /**
     * Recommended 50–60 characters
     */
    title?: string | null;
    /**
     * Recommended 150–160 characters
     */
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * Excludes this page from sitemap and sets noindex/nofollow
     */
    noIndex?: boolean | null;
    /**
     * Leave blank to auto-generate from page URL
     */
    canonical?: string | null;
    /**
     * Used for Facebook/LinkedIn sharing (defaults to Meta Title if blank)
     */
    ogTitle?: string | null;
    /**
     * Used for social sharing cards (defaults to Meta Description if blank)
     */
    ogDescription?: string | null;
  };
  seo?: {
    /**
     * One plain-English sentence describing this page for AI tools (ChatGPT, Perplexity, Claude)
     */
    llmsEntry?: string | null;
    /**
     * Semantic topic tags for AI crawlers and internal search
     */
    topics?:
      | {
          topic: string;
          id?: string | null;
        }[]
      | null;
    contentType?: ('landing' | 'article' | 'job' | 'portfolio' | 'faq') | null;
    /**
     * Brief description of intended reader, e.g. "CTOs at Series A startups"
     */
    targetAudience?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-friendly identifier, auto-generated from category name.
   */
  slug: string;
  description?: string | null;
  /**
   * e.g. #4f46e5
   */
  color?: string | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  title: string;
  /**
   * URL-friendly identifier, e.g. "payflow-banking"
   */
  slug: string;
  featuredImage?: (number | null) | Media;
  /**
   * Select one or more categories. The first category becomes the primary tag on grid cards.
   */
  categories?: (number | PortfolioCategory)[] | null;
  /**
   * Brief summary shown on portfolio grid cards (1–2 sentences).
   */
  excerpt?: string | null;
  /**
   * Full project overview shown on the portfolio detail page (left column).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Stats shown in the sidebar on portfolio detail pages (e.g. "500K+ Active Users").
   */
  keyMetrics?:
    | {
        metricValue?: string | null;
        metricLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  client?: string | null;
  duration?: string | null;
  year?: string | null;
  teamSize?: string | null;
  publishedAt?: string | null;
  status: 'draft' | 'published';
  relatedProjects?: (number | Portfolio)[] | null;
  meta?: {
    /**
     * Recommended 50–60 characters
     */
    title?: string | null;
    /**
     * Recommended 150–160 characters
     */
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * Excludes this page from sitemap and sets noindex/nofollow
     */
    noIndex?: boolean | null;
    /**
     * Leave blank to auto-generate from page URL
     */
    canonical?: string | null;
    /**
     * Used for Facebook/LinkedIn sharing (defaults to Meta Title if blank)
     */
    ogTitle?: string | null;
    /**
     * Used for social sharing cards (defaults to Meta Description if blank)
     */
    ogDescription?: string | null;
  };
  seo?: {
    /**
     * One plain-English sentence describing this page for AI tools (ChatGPT, Perplexity, Claude)
     */
    llmsEntry?: string | null;
    /**
     * Semantic topic tags for AI crawlers and internal search
     */
    topics?:
      | {
          topic: string;
          id?: string | null;
        }[]
      | null;
    contentType?: ('landing' | 'article' | 'job' | 'portfolio' | 'faq') | null;
    /**
     * Brief description of intended reader, e.g. "CTOs at Series A startups"
     */
    targetAudience?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories".
 */
export interface PortfolioCategory {
  id: number;
  name: string;
  /**
   * URL-friendly identifier, auto-generated from category name.
   */
  slug: string;
  /**
   * Optional parent category for hierarchical grouping (e.g. "Web Apps" under "Digital Products").
   */
  parent?: (number | null) | PortfolioCategory;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-categories".
 */
export interface FaqCategory {
  id: number;
  /**
   * Sidebar label, e.g. "General"
   */
  name: string;
  /**
   * Heading shown in main content area, e.g. "General FAQs"
   */
  title: string;
  /**
   * URL-friendly identifier, e.g. "general"
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * The FAQ category this question belongs to.
   */
  category: number | FaqCategory;
  question: string;
  answer?: string | null;
  /**
   * Lower numbers appear first within a category.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  avatar?: (number | null) | Media;
  clientName: string;
  clientRole?: string | null;
  clientCompany?: string | null;
  quote: string;
  rating?: number | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-vacancies".
 */
export interface JobVacancy {
  id: number;
  title: string;
  positionType: 'full-time' | 'part-time' | 'contract' | 'remote' | 'internship' | 'freelance';
  category?: string | null;
  location?: string | null;
  /**
   * One or two lines shown in the jobs-list block. Keep it brief.
   */
  excerpt?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  applyLabel?: string | null;
  applyUrl?: string | null;
  status: 'active' | 'closed';
  /**
   * Lower numbers appear first in the listing.
   */
  order?: number | null;
  meta?: {
    /**
     * Recommended 50–60 characters
     */
    title?: string | null;
    /**
     * Recommended 150–160 characters
     */
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * Excludes this page from sitemap and sets noindex/nofollow
     */
    noIndex?: boolean | null;
    /**
     * Leave blank to auto-generate from page URL
     */
    canonical?: string | null;
    /**
     * Used for Facebook/LinkedIn sharing (defaults to Meta Title if blank)
     */
    ogTitle?: string | null;
    /**
     * Used for social sharing cards (defaults to Meta Description if blank)
     */
    ogDescription?: string | null;
  };
  seo?: {
    /**
     * One plain-English sentence describing this page for AI tools (ChatGPT, Perplexity, Claude)
     */
    llmsEntry?: string | null;
    /**
     * Semantic topic tags for AI crawlers and internal search
     */
    topics?:
      | {
          topic: string;
          id?: string | null;
        }[]
      | null;
    contentType?: ('landing' | 'article' | 'job' | 'portfolio' | 'faq') | null;
    /**
     * Brief description of intended reader, e.g. "CTOs at Series A startups"
     */
    targetAudience?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests".
 */
export interface QuoteRequest {
  id: number;
  firstName: string;
  lastName?: string | null;
  email: string;
  phone?: string | null;
  company?: string | null;
  serviceType?:
    | ('Web Development' | 'Mobile Development' | 'IT Consulting' | 'HR Recruitment' | 'Cloud Solutions')
    | null;
  serviceSelected?: string | null;
  developmentTime?: ('1–3 months' | '3–6 months' | '6–12 months' | '12+ months') | null;
  itemsCount?: number | null;
  calculatedCost?: number | null;
  maintenanceFee?: number | null;
  projectDetails: string;
  status?: ('new' | 'reviewing' | 'quoted' | 'won' | 'lost') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugins".
 */
export interface Plugin {
  id: number;
  name: string;
  /**
   * Unique identifier. Built-in plugins use reserved slugs (e.g. "layout-builder").
   */
  slug: string;
  description?: string | null;
  pluginType?:
    | ('built-in' | 'frontend-script' | 'block-extension' | 'third-party-embed' | 'integration' | 'utility')
    | null;
  category?: ('layout' | 'content' | 'media' | 'analytics' | 'seo' | 'ecommerce' | 'utility') | null;
  status: 'active' | 'inactive';
  version?: string | null;
  author?: string | null;
  icon?: (number | null) | Media;
  /**
   * Inline HTML/JS code to inject into the frontend (for frontend-script and third-party-embed types).
   */
  scriptCode?: string | null;
  /**
   * Upload a plugin file (.zip, .js, .ts) for block-extension plugins.
   */
  pluginFile?: (number | null) | Media;
  /**
   * Plugin-specific configuration as key-value pairs.
   */
  settings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Features provided by this plugin.
   */
  features?:
    | {
        featureName: string;
        featureDescription?: string | null;
        featureType?: ('collection' | 'field' | 'hook' | 'script') | null;
        id?: string | null;
      }[]
    | null;
  autoActivate?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks".
 */
export interface Block {
  id: number;
  name: string;
  blockType:
    | '__basic_header__'
    | 'container'
    | 'grid'
    | 'heading'
    | 'text-editor'
    | 'image'
    | 'video'
    | 'button'
    | 'divider'
    | 'spacer'
    | 'google-map'
    | 'icon'
    | '__general_header__'
    | 'tabs'
    | 'accordion'
    | 'image-box'
    | 'icon-box'
    | 'image-carousel'
    | 'basic-gallery'
    | 'icon-list'
    | 'counter'
    | 'progress-bar'
    | 'testimonial'
    | 'social-icons'
    | 'alert'
    | 'html'
    | 'hero-section'
    | 'services-section'
    | 'testimonials-section'
    | 'contact-section'
    | '__home_header__'
    | 'home-hero'
    | 'home-about'
    | 'home-services'
    | 'home-testimonials'
    | 'home-contact'
    | '__about_header__'
    | 'about-hero'
    | 'about-company'
    | 'about-mission-vision'
    | 'about-leadership'
    | 'about-faq'
    | 'about-contact'
    | '__service_header__'
    | 'web-dev-hero'
    | 'service-cards'
    | 'process-steps'
    | 'cta-banner'
    | 'hr-recruit-expertise'
    | '__contact_header__'
    | 'contact-hero'
    | 'contact-stats'
    | 'contact-locations'
    | '__content_header__'
    | 'insight-hero'
    | 'insight-articles'
    | 'article-hero'
    | 'article-featured'
    | 'article-grid'
    | 'portfolio-hero'
    | 'portfolio-statistics'
    | 'portfolio-main'
    | 'project-grid'
    | 'faq-main'
    | '__get_involved_header__'
    | 'get-involved-hero'
    | 'get-involved-quote'
    | 'get-involved-jobs'
    | 'get-involved-culture'
    | 'get-involved-cta'
    | 'community-hero'
    | 'community-channels'
    | 'community-ambassador'
    | 'community-programs'
    | '__who_we_serve_header__'
    | 'who-we-serve-hero'
    | 'who-we-serve-industries'
    | 'who-we-serve-why'
    | '__portfolio_detail_header__'
    | 'portfolio-detail-top'
    | 'portfolio-featured-image'
    | 'portfolio-detail-overview'
    | '__article_detail_header__'
    | 'article-detail-hero'
    | 'article-detail-content'
    | 'article-related'
    | '__forms_header__'
    | 'dynamic-form'
    | 'form';
  category:
    | 'basic'
    | 'general'
    | 'home-sections'
    | 'about-sections'
    | 'service-sections'
    | 'contact-sections'
    | 'content-sections'
    | 'get-involved-sections'
    | 'who-we-serve-sections'
    | 'portfolio-sections'
    | 'article-sections'
    | 'form-sections';
  title?: string | null;
  subtitle?: string | null;
  image?: (number | null) | Media;
  /**
   * YouTube or Vimeo URL
   */
  videoUrl?: string | null;
  buttonLabel?: string | null;
  buttonUrl?: string | null;
  /**
   * Raw HTML markup (html block) — or badge/CTA heading text for section blocks
   */
  htmlContent?: string | null;
  /**
   * Paste the embed URL from Google Maps → Share → Embed a map
   */
  mapEmbedUrl?: string | null;
  /**
   * Icon identifier or inline SVG string
   */
  iconName?: string | null;
  columns?: ('1' | '2' | '3' | '4' | '6') | null;
  alertType?: ('info' | 'success' | 'warning' | 'error') | null;
  items?:
    | {
        label?: string | null;
        content?: string | null;
        image?: (number | null) | Media;
        icon?: string | null;
        value?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  badge?: string | null;
  heading?: string | null;
  body?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaPrimaryUrl?: string | null;
  ctaSecondaryLabel?: string | null;
  ctaSecondaryUrl?: string | null;
  heroImage?: (number | null) | Media;
  heroStats?:
    | {
        statValue?: string | null;
        statLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  floatingCards?:
    | {
        cardText?: string | null;
        cardPosition?: ('top-right' | 'bottom-left' | 'top-left' | 'bottom-right') | null;
        cardIcon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  pillars?:
    | {
        pillarIcon?: (number | null) | Media;
        pillarTitle?: string | null;
        pillarDesc?: string | null;
        id?: string | null;
      }[]
    | null;
  subheading?: string | null;
  serviceItems?:
    | {
        serviceIcon?: (number | null) | Media;
        serviceTitle?: string | null;
        serviceDesc?: string | null;
        serviceHref?: string | null;
        id?: string | null;
      }[]
    | null;
  customSolutionHeading?: string | null;
  customSolutionBody?: string | null;
  customSolutionCtaLabel?: string | null;
  customSolutionCtaUrl?: string | null;
  testimonialsContentSource?: ('collection' | 'manual') | null;
  /**
   * Max testimonials to load from the collection.
   */
  testimonialsLimit?: number | null;
  enableCarousel?: boolean | null;
  testimonialItems?:
    | {
        clientName?: string | null;
        clientRole?: string | null;
        clientCompany?: string | null;
        quote?: string | null;
        rating?: number | null;
        avatar?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  contactSubheading?: string | null;
  formHeading?: string | null;
  submitLabel?: string | null;
  infoHeading?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  contactLocation?: string | null;
  badgeIcon?: (number | null) | Media;
  aboutHeroHeading?: string | null;
  aboutHeroSubheading?: string | null;
  aboutHeroVideoUrl?: string | null;
  aboutCompanyHeading?: string | null;
  body1?: string | null;
  body2?: string | null;
  companyStats?:
    | {
        statValue?: string | null;
        statLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  companyImage?: (number | null) | Media;
  missionIcon?: (number | null) | Media;
  missionHeading?: string | null;
  missionBody?: string | null;
  visionIcon?: (number | null) | Media;
  visionHeading?: string | null;
  visionBody?: string | null;
  valuesHeading?: string | null;
  values?:
    | {
        valueIcon?: (number | null) | Media;
        valueTitle?: string | null;
        valueDesc?: string | null;
        id?: string | null;
      }[]
    | null;
  leadershipHeading?: string | null;
  leadershipSubheading?: string | null;
  teamMembers?:
    | {
        avatar?: (number | null) | Media;
        memberName?: string | null;
        memberRole?: string | null;
        memberBio?: string | null;
        id?: string | null;
      }[]
    | null;
  faqContentSource?: ('collection' | 'manual') | null;
  /**
   * Optional: load only FAQs from this category slug (faq-section only).
   */
  faqCategorySlug?: string | null;
  /**
   * Max FAQ items to load from the collection.
   */
  faqLimit?: number | null;
  faqBackLabel?: string | null;
  faqBackUrl?: string | null;
  faqHeading?: string | null;
  faqSubheading?: string | null;
  faqItems?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  badgeIconSrc?: string | null;
  breadcrumbItems?:
    | {
        breadcrumbLabel: string;
        breadcrumbUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  cardItems?:
    | {
        cardIconSrc?: string | null;
        cardTitle: string;
        cardDescription?: string | null;
        /**
         * Enter each feature on a new line
         */
        cardFeatures?: string | null;
        id?: string | null;
      }[]
    | null;
  showCategoryFilter?: ('yes' | 'no') | null;
  projectContentSource?: ('collection' | 'manual') | null;
  /**
   * Max portfolio items to load from the collection.
   */
  projectLimit?: number | null;
  /**
   * Optional: show only items from this portfolio-category slug.
   */
  projectCategory?: string | null;
  projectOrderBy?: ('publishedAt_desc' | 'publishedAt_asc') | null;
  projectHeading?: string | null;
  projectSubheading?: string | null;
  projectItems?:
    | {
        projectImage?: (number | null) | Media;
        projectTag?: string | null;
        projectType?: string | null;
        projectTitle: string;
        projectDesc?: string | null;
        projectCta?: string | null;
        projectUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  backLabel?: string | null;
  backUrl?: string | null;
  tags?:
    | {
        tagLabel: string;
        id?: string | null;
      }[]
    | null;
  pdTitle?: string | null;
  pdDescription?: string | null;
  pdClient?: string | null;
  pdDuration?: string | null;
  pdYear?: string | null;
  pdTeamSize?: string | null;
  pdCaption?: string | null;
  pdSectionTitle?: string | null;
  /**
   * Separate paragraphs with a blank line.
   */
  pdContent?: string | null;
  pdMetricsTitle?: string | null;
  pdMetrics?:
    | {
        pdMetricValue?: string | null;
        pdMetricLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  portfolioHeroBadge?: string | null;
  portfolioHeroHeading?: string | null;
  portfolioHeroSubheading?: string | null;
  portfolioHeroCtaPrimaryLabel?: string | null;
  portfolioHeroCtaPrimaryUrl?: string | null;
  portfolioHeroCtaSecondaryLabel?: string | null;
  portfolioHeroCtaSecondaryUrl?: string | null;
  portfolioStats?:
    | {
        statValue?: string | null;
        statLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  featContentSource?: ('collection' | 'manual') | null;
  /**
   * Slug of the post to feature (e.g. "my-first-post").
   */
  featPostSlug?: string | null;
  /**
   * Select the form to render on this page.
   */
  formRef?: (number | null) | Form;
  formSubmitLabel?: string | null;
  /**
   * Select the form to display inside this styled section.
   */
  surveyFormRef?: (number | null) | Form;
  textAlign?: ('left' | 'center' | 'right' | 'justify') | null;
  fontFamily?: string | null;
  fontSize?: string | null;
  fontWeight?: string | null;
  lineHeight?: string | null;
  letterSpacing?: string | null;
  paragraphSpacing?: string | null;
  textShadowX?: string | null;
  textShadowY?: string | null;
  textShadowBlur?: string | null;
  textShadowColor?: string | null;
  textColorNormal?: string | null;
  textColorHover?: string | null;
  linkColorNormal?: string | null;
  linkColorHover?: string | null;
  backgroundColor?: string | null;
  borderRadius?: string | null;
  /**
   * Additional CSS rules for this block
   */
  customCSS?: string | null;
  paddingTop?: string | null;
  paddingRight?: string | null;
  paddingBottom?: string | null;
  paddingLeft?: string | null;
  marginTop?: string | null;
  marginRight?: string | null;
  marginBottom?: string | null;
  marginLeft?: string | null;
  width?: string | null;
  position?: ('static' | 'relative' | 'absolute' | 'fixed' | 'sticky') | null;
  zIndex?: number | null;
  cssClassName?: string | null;
  htmlId?: string | null;
  hideOnMobile?: boolean | null;
  hideOnTablet?: boolean | null;
  hideOnDesktop?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action:
    | 'login'
    | 'logout'
    | 'failed-login'
    | 'create'
    | 'update'
    | 'delete'
    | 'ip-blocked'
    | '2fa-enabled'
    | '2fa-verified'
    | 'ip-unlocked';
  collection?: string | null;
  documentId?: string | null;
  user?: (number | null) | User;
  ip?: string | null;
  userAgent?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "security-events".
 */
export interface SecurityEvent {
  id: number;
  eventType: 'failed-login' | 'rate-limit-hit' | 'ip-blocked' | 'upload-rejected';
  ip?: string | null;
  userId?: string | null;
  endpoint?: string | null;
  count?: number | null;
  /**
   * When this lockout/block expires (null = permanent)
   */
  expiresAt?: string | null;
  resolved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions captured by the chatbot widget
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-leads".
 */
export interface ChatbotLead {
  id: number;
  name: string;
  email: string;
  /**
   * Node label that triggered the contact form
   */
  question?: string | null;
  /**
   * Full breadcrumb of nodes the user clicked through
   */
  conversationPath?: string | null;
  /**
   * Page the user was on when they submitted the form
   */
  page?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Analytics — tracks widget opens, node clicks, WhatsApp taps, and lead submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-events".
 */
export interface ChatbotEvent {
  id: number;
  eventType:
    | 'widget_opened'
    | 'node_selected'
    | 'answer_viewed'
    | 'whatsapp_clicked'
    | 'contact_form_shown'
    | 'lead_submitted'
    | 'widget_closed'
    | 'back_navigated';
  nodeLabel?: string | null;
  /**
   * Breadcrumb of nodes clicked, e.g. "Services > Web Dev > Cost"
   */
  conversationPath?: string | null;
  page?: string | null;
  /**
   * Anonymous session ID from localStorage
   */
  sessionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  status?: ('new' | 'in-review' | 'contacted' | 'closed') | null;
  statusUpdatedAt?: string | null;
  /**
   * Auto-calculated (0–100)
   */
  score?: number | null;
  /**
   * Scoring detail (JSON)
   */
  scoreBreakdown?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'pages';
        value: number | Page;
      };
  excerpt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'portfolio-categories';
        value: number | PortfolioCategory;
      } | null)
    | ({
        relationTo: 'faq-categories';
        value: number | FaqCategory;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'job-vacancies';
        value: number | JobVacancy;
      } | null)
    | ({
        relationTo: 'quote-requests';
        value: number | QuoteRequest;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'plugins';
        value: number | Plugin;
      } | null)
    | ({
        relationTo: 'blocks';
        value: number | Block;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'security-events';
        value: number | SecurityEvent;
      } | null)
    | ({
        relationTo: 'chatbot-leads';
        value: number | ChatbotLead;
      } | null)
    | ({
        relationTo: 'chatbot-events';
        value: number | ChatbotEvent;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  showAdminMenu?: T;
  twoFactorEnabled?: T;
  twoFactorSecret?: T;
  twoFactorBackupCodes?:
    | T
    | {
        code?: T;
        id?: T;
      };
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  layoutBuilder?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        cardsGrid?:
          | T
          | {
              heading?: T;
              subheading?: T;
              cards?:
                | T
                | {
                    image?: T;
                    heading?: T;
                    body?: T;
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    number?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              url?: T;
              caption?: T;
              poster?: T;
              id?: T;
              blockName?: T;
            };
        formBlock?:
          | T
          | {
              heading?: T;
              subheading?: T;
              form?: T;
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              message?: T;
              type?: T;
              dismissible?: T;
              id?: T;
              blockName?: T;
            };
        code?:
          | T
          | {
              language?: T;
              code?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  publishedAt?: T;
  status?: T;
  pageTemplate?: T;
  isFrontpage?: T;
  portfolioDetailTemplate?: T;
  articleDetailTemplate?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  seo?:
    | T
    | {
        llmsEntry?: T;
        topics?:
          | T
          | {
              topic?: T;
              id?: T;
            };
        contentType?: T;
        targetAudience?: T;
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  categories?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  publishedAt?: T;
  status?: T;
  featured?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  seo?:
    | T
    | {
        llmsEntry?: T;
        topics?:
          | T
          | {
              topic?: T;
              id?: T;
            };
        contentType?: T;
        targetAudience?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  categories?: T;
  excerpt?: T;
  content?: T;
  keyMetrics?:
    | T
    | {
        metricValue?: T;
        metricLabel?: T;
        id?: T;
      };
  client?: T;
  duration?: T;
  year?: T;
  teamSize?: T;
  publishedAt?: T;
  status?: T;
  relatedProjects?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  seo?:
    | T
    | {
        llmsEntry?: T;
        topics?:
          | T
          | {
              topic?: T;
              id?: T;
            };
        contentType?: T;
        targetAudience?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories_select".
 */
export interface PortfolioCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-categories_select".
 */
export interface FaqCategoriesSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  category?: T;
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  avatar?: T;
  clientName?: T;
  clientRole?: T;
  clientCompany?: T;
  quote?: T;
  rating?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-vacancies_select".
 */
export interface JobVacanciesSelect<T extends boolean = true> {
  title?: T;
  positionType?: T;
  category?: T;
  location?: T;
  excerpt?: T;
  description?: T;
  applyLabel?: T;
  applyUrl?: T;
  status?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  seo?:
    | T
    | {
        llmsEntry?: T;
        topics?:
          | T
          | {
              topic?: T;
              id?: T;
            };
        contentType?: T;
        targetAudience?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests_select".
 */
export interface QuoteRequestsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  company?: T;
  serviceType?: T;
  serviceSelected?: T;
  developmentTime?: T;
  itemsCount?: T;
  calculatedCost?: T;
  maintenanceFee?: T;
  projectDetails?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugins_select".
 */
export interface PluginsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  pluginType?: T;
  category?: T;
  status?: T;
  version?: T;
  author?: T;
  icon?: T;
  scriptCode?: T;
  pluginFile?: T;
  settings?: T;
  features?:
    | T
    | {
        featureName?: T;
        featureDescription?: T;
        featureType?: T;
        id?: T;
      };
  autoActivate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks_select".
 */
export interface BlocksSelect<T extends boolean = true> {
  name?: T;
  blockType?: T;
  category?: T;
  title?: T;
  subtitle?: T;
  image?: T;
  videoUrl?: T;
  buttonLabel?: T;
  buttonUrl?: T;
  htmlContent?: T;
  mapEmbedUrl?: T;
  iconName?: T;
  columns?: T;
  alertType?: T;
  items?:
    | T
    | {
        label?: T;
        content?: T;
        image?: T;
        icon?: T;
        value?: T;
        url?: T;
        id?: T;
      };
  badge?: T;
  heading?: T;
  body?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryUrl?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryUrl?: T;
  heroImage?: T;
  heroStats?:
    | T
    | {
        statValue?: T;
        statLabel?: T;
        id?: T;
      };
  floatingCards?:
    | T
    | {
        cardText?: T;
        cardPosition?: T;
        cardIcon?: T;
        id?: T;
      };
  description?: T;
  pillars?:
    | T
    | {
        pillarIcon?: T;
        pillarTitle?: T;
        pillarDesc?: T;
        id?: T;
      };
  subheading?: T;
  serviceItems?:
    | T
    | {
        serviceIcon?: T;
        serviceTitle?: T;
        serviceDesc?: T;
        serviceHref?: T;
        id?: T;
      };
  customSolutionHeading?: T;
  customSolutionBody?: T;
  customSolutionCtaLabel?: T;
  customSolutionCtaUrl?: T;
  testimonialsContentSource?: T;
  testimonialsLimit?: T;
  enableCarousel?: T;
  testimonialItems?:
    | T
    | {
        clientName?: T;
        clientRole?: T;
        clientCompany?: T;
        quote?: T;
        rating?: T;
        avatar?: T;
        id?: T;
      };
  contactSubheading?: T;
  formHeading?: T;
  submitLabel?: T;
  infoHeading?: T;
  contactEmail?: T;
  contactPhone?: T;
  contactLocation?: T;
  badgeIcon?: T;
  aboutHeroHeading?: T;
  aboutHeroSubheading?: T;
  aboutHeroVideoUrl?: T;
  aboutCompanyHeading?: T;
  body1?: T;
  body2?: T;
  companyStats?:
    | T
    | {
        statValue?: T;
        statLabel?: T;
        id?: T;
      };
  companyImage?: T;
  missionIcon?: T;
  missionHeading?: T;
  missionBody?: T;
  visionIcon?: T;
  visionHeading?: T;
  visionBody?: T;
  valuesHeading?: T;
  values?:
    | T
    | {
        valueIcon?: T;
        valueTitle?: T;
        valueDesc?: T;
        id?: T;
      };
  leadershipHeading?: T;
  leadershipSubheading?: T;
  teamMembers?:
    | T
    | {
        avatar?: T;
        memberName?: T;
        memberRole?: T;
        memberBio?: T;
        id?: T;
      };
  faqContentSource?: T;
  faqCategorySlug?: T;
  faqLimit?: T;
  faqBackLabel?: T;
  faqBackUrl?: T;
  faqHeading?: T;
  faqSubheading?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  badgeIconSrc?: T;
  breadcrumbItems?:
    | T
    | {
        breadcrumbLabel?: T;
        breadcrumbUrl?: T;
        id?: T;
      };
  cardItems?:
    | T
    | {
        cardIconSrc?: T;
        cardTitle?: T;
        cardDescription?: T;
        cardFeatures?: T;
        id?: T;
      };
  showCategoryFilter?: T;
  projectContentSource?: T;
  projectLimit?: T;
  projectCategory?: T;
  projectOrderBy?: T;
  projectHeading?: T;
  projectSubheading?: T;
  projectItems?:
    | T
    | {
        projectImage?: T;
        projectTag?: T;
        projectType?: T;
        projectTitle?: T;
        projectDesc?: T;
        projectCta?: T;
        projectUrl?: T;
        id?: T;
      };
  backLabel?: T;
  backUrl?: T;
  tags?:
    | T
    | {
        tagLabel?: T;
        id?: T;
      };
  pdTitle?: T;
  pdDescription?: T;
  pdClient?: T;
  pdDuration?: T;
  pdYear?: T;
  pdTeamSize?: T;
  pdCaption?: T;
  pdSectionTitle?: T;
  pdContent?: T;
  pdMetricsTitle?: T;
  pdMetrics?:
    | T
    | {
        pdMetricValue?: T;
        pdMetricLabel?: T;
        id?: T;
      };
  portfolioHeroBadge?: T;
  portfolioHeroHeading?: T;
  portfolioHeroSubheading?: T;
  portfolioHeroCtaPrimaryLabel?: T;
  portfolioHeroCtaPrimaryUrl?: T;
  portfolioHeroCtaSecondaryLabel?: T;
  portfolioHeroCtaSecondaryUrl?: T;
  portfolioStats?:
    | T
    | {
        statValue?: T;
        statLabel?: T;
        id?: T;
      };
  featContentSource?: T;
  featPostSlug?: T;
  formRef?: T;
  formSubmitLabel?: T;
  surveyFormRef?: T;
  textAlign?: T;
  fontFamily?: T;
  fontSize?: T;
  fontWeight?: T;
  lineHeight?: T;
  letterSpacing?: T;
  paragraphSpacing?: T;
  textShadowX?: T;
  textShadowY?: T;
  textShadowBlur?: T;
  textShadowColor?: T;
  textColorNormal?: T;
  textColorHover?: T;
  linkColorNormal?: T;
  linkColorHover?: T;
  backgroundColor?: T;
  borderRadius?: T;
  customCSS?: T;
  paddingTop?: T;
  paddingRight?: T;
  paddingBottom?: T;
  paddingLeft?: T;
  marginTop?: T;
  marginRight?: T;
  marginBottom?: T;
  marginLeft?: T;
  width?: T;
  position?: T;
  zIndex?: T;
  cssClassName?: T;
  htmlId?: T;
  hideOnMobile?: T;
  hideOnTablet?: T;
  hideOnDesktop?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  collection?: T;
  documentId?: T;
  user?: T;
  ip?: T;
  userAgent?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "security-events_select".
 */
export interface SecurityEventsSelect<T extends boolean = true> {
  eventType?: T;
  ip?: T;
  userId?: T;
  endpoint?: T;
  count?: T;
  expiresAt?: T;
  resolved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-leads_select".
 */
export interface ChatbotLeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  question?: T;
  conversationPath?: T;
  page?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-events_select".
 */
export interface ChatbotEventsSelect<T extends boolean = true> {
  eventType?: T;
  nodeLabel?: T;
  conversationPath?: T;
  page?: T;
  sessionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        stepSeparator?:
          | T
          | {
              stepLabel?: T;
              stepDescription?: T;
              id?: T;
              blockName?: T;
            };
        scale?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              scaleMin?: T;
              scaleMax?: T;
              minLabel?: T;
              maxLabel?: T;
              scoreWeight?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  scoring?:
    | T
    | {
        enabled?: T;
        completenessWeight?: T;
        fieldWeights?:
          | T
          | {
              fieldName?: T;
              matchValue?: T;
              points?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  status?: T;
  statusUpdatedAt?: T;
  score?: T;
  scoreBreakdown?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  excerpt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  menuItems?:
    | {
        label: string;
        url?: string | null;
        openInNewTab?: boolean | null;
        megaMenu?: boolean | null;
        /**
         * Visual layout for the mega menu dropdown.
         */
        megaMenuStyle?: ('with-description' | 'category-grid' | 'no-icon') | null;
        /**
         * Add columns of links that appear in the dropdown panel.
         */
        columns?:
          | {
              columnTitle?: string | null;
              links?:
                | {
                    label: string;
                    url: string;
                    description?: string | null;
                    icon?: (number | null) | Media;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional promotional card shown on the right side of the mega menu.
         */
        featured?: {
          title?: string | null;
          description?: string | null;
          url?: string | null;
          cta?: string | null;
          image?: (number | null) | Media;
        };
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Links shown in the footer bottom bar (e.g. Privacy Policy, Terms of Service).
   */
  footerCopyrightMenu?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  ogImage?: (number | null) | Media;
  /**
   * When enabled, all frontend pages redirect to the maintenance page.
   */
  maintenanceMode?: boolean | null;
  maintenanceTitle?: string | null;
  maintenanceMessage?: string | null;
  maintenanceStatusLabel?: string | null;
  maintenanceEstimate?: string | null;
  fromName?: string | null;
  fromEmail?: string | null;
  adminNotificationEmail?: string | null;
  /**
   * When enabled, the values below are used instead of SMTP_HOST / SMTP_USER env vars.
   */
  smtpEnabled?: boolean | null;
  smtpHost?: string | null;
  smtpPort?: number | null;
  /**
   * Enable for port 465. Disable (STARTTLS) for port 587.
   */
  smtpSecure?: boolean | null;
  smtpUser?: string | null;
  /**
   * Stored encrypted. Leave blank to keep existing value.
   */
  smtpPassword?: string | null;
  /**
   * Define which roles can perform each action on each collection. Admin role always has full access.
   */
  accessControl?:
    | {
        collection: 'pages' | 'posts' | 'categories' | 'media' | 'users' | 'navigation' | 'blocks';
        canRead?: ('admin' | 'editor' | 'viewer')[] | null;
        canCreate?: ('admin' | 'editor' | 'viewer')[] | null;
        canUpdate?: ('admin' | 'editor' | 'viewer')[] | null;
        canDelete?: ('admin' | 'editor' | 'viewer')[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. G-XXXXXXXXXX
   */
  googleAnalyticsId?: string | null;
  stripeEnabled?: boolean | null;
  /**
   * Number of failed attempts before lockout.
   */
  loginMaxAttempts?: number | null;
  /**
   * How long the lockout lasts. 0 = permanent until manually unlocked.
   */
  loginLockoutMinutes?: number | null;
  /**
   * When enforced, users must enroll 2FA on next login.
   */
  requireTwoFactor?: ('disabled' | 'admins-only' | 'all-users') | null;
  /**
   * When enabled, blocklist and allowlist rules are enforced on /admin.
   */
  ipFilterEnabled?: boolean | null;
  /**
   * IPs that are always denied access to /admin.
   */
  ipBlocklist?:
    | {
        ip: string;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * If non-empty, only these IPs can access /admin. Leave empty to allow all non-blocked IPs.
   */
  ipAllowlist?:
    | {
        ip: string;
        id?: string | null;
      }[]
    | null;
  apiRateLimitEnabled?: boolean | null;
  apiRateLimitMax?: number | null;
  cspEnabled?: boolean | null;
  /**
   * Log violations instead of blocking — useful when first rolling out CSP.
   */
  cspReportOnly?: boolean | null;
  /**
   * Only enable on HTTPS deployments.
   */
  hstsEnabled?: boolean | null;
  /**
   * Base URL used for canonical tags and sitemap. No trailing slash.
   */
  canonicalDomain?: string | null;
  /**
   * Paths crawlers should not index, e.g. /admin, /api
   */
  robotsDisallow?:
    | {
        path: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional crawl delay directive for robots.txt
   */
  crawlDelay?: number | null;
  /**
   * Serve a machine-readable /llms.txt for AI assistants
   */
  llmsTxtEnabled?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  siteName?: string | null;
  siteTagline?: string | null;
  /**
   * Used in header and footer. Recommended: SVG or PNG, max 200×60px.
   */
  logo?: (number | null) | Media;
  /**
   * Browser tab icon. Recommended: 32×32 or 64×64 PNG.
   */
  favicon?: (number | null) | Media;
  /**
   * Pick a preset palette or choose "Custom Colors" to set individual values below.
   */
  colorPreset?:
    | (
        | 'dark-default'
        | 'light-default'
        | 'ocean-blue'
        | 'midnight-navy'
        | 'forest-green'
        | 'corporate-light'
        | 'sunset-orange'
        | 'custom'
      )
    | null;
  /**
   * Used as default baseline when "Custom Colors" is selected above.
   */
  colorScheme?: ('dark' | 'light') | null;
  /**
   * Buttons, links, highlights
   */
  primaryColor?: string | null;
  /**
   * Gradients, badges
   */
  secondaryColor?: string | null;
  bgColor?: string | null;
  surfaceColor?: string | null;
  textColor?: string | null;
  mutedColor?: string | null;
  borderColor?: string | null;
  /**
   * Background for the testimonials section
   */
  testimonialsBg?: string | null;
  /**
   * A preset palette is active. Switch to "Custom Colors" above to edit individual values.
   */
  presetPreviewNote?: string | null;
  headingFont?: ('syne' | 'raleway' | 'poppins' | 'playfair' | 'inter') | null;
  bodyFont?: ('dm-sans' | 'inter' | 'source-sans' | 'nunito') | null;
  footerDescription?: string | null;
  footerCopyright?: string | null;
  getStartedTitle?: string | null;
  getStartedDesc?: string | null;
  getStartedButtonLabel?: string | null;
  getStartedButtonUrl?: string | null;
  twitter?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  github?: string | null;
  /**
   * Raw CSS injected into <head> on every frontend page. Overrides any theme variables. Use sparingly.
   */
  customCSS?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the chatbot widget — greeting, Q&A tree, WhatsApp, visibility
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-settings".
 */
export interface ChatbotSetting {
  id: number;
  /**
   * Toggle to show/hide the chatbot widget on the frontend
   */
  active?: boolean | null;
  botName?: string | null;
  greetingMessage?: string | null;
  /**
   * Fallback used when a node has no WhatsApp URL override
   */
  defaultWhatsappUrl?: string | null;
  contactFormTitle?: string | null;
  /**
   * Email address to notify when a contact form is submitted. Leave empty to disable.
   */
  notifyEmail?: string | null;
  /**
   * Root-level options shown after the greeting. Each option can have sub-questions (3 levels deep via admin; unlimited depth is supported programmatically).
   */
  nodes?:
    | {
        /**
         * Text shown to user as a clickable option
         */
        label: string;
        /**
         * Bot reply when user picks this option. Leave empty if using sub-questions.
         */
        answer?: string | null;
        /**
         * Shows name + email form 3 seconds after answer is displayed
         */
        showContactForm?: boolean | null;
        showWhatsapp?: boolean | null;
        /**
         * Leave empty to use the global default WhatsApp URL
         */
        whatsappUrl?: string | null;
        /**
         * Optional follow-up questions shown after this option is selected
         */
        children?:
          | {
              /**
               * Text shown to user as a clickable option
               */
              label: string;
              /**
               * Bot reply when user picks this option. Leave empty if using sub-questions.
               */
              answer?: string | null;
              /**
               * Shows name + email form 3 seconds after answer is displayed
               */
              showContactForm?: boolean | null;
              showWhatsapp?: boolean | null;
              /**
               * Leave empty to use the global default WhatsApp URL
               */
              whatsappUrl?: string | null;
              /**
               * Optional further follow-up questions
               */
              subChildren?:
                | {
                    /**
                     * Text shown to user as a clickable option
                     */
                    label: string;
                    /**
                     * Bot reply when user picks this option. Leave empty if using sub-questions.
                     */
                    answer?: string | null;
                    /**
                     * Shows name + email form 3 seconds after answer is displayed
                     */
                    showContactForm?: boolean | null;
                    showWhatsapp?: boolean | null;
                    /**
                     * Leave empty to use the global default WhatsApp URL
                     */
                    whatsappUrl?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When enabled, widget appears on every frontend page. Disable to use the whitelist.
   */
  showOnAllPages?: boolean | null;
  /**
   * Only active when "Show on All Pages" is off. Use exact paths, e.g. "/" for home, "/contact".
   */
  pageWhitelist?:
    | {
        path: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show an offline message outside of business hours (HKT timezone)
   */
  availabilityEnabled?: boolean | null;
  availabilityStart?: number | null;
  availabilityEnd?: number | null;
  availabilityMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure multilanguage routing, switcher, and active locales.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "language-settings".
 */
export interface LanguageSetting {
  id: number;
  /**
   * Enable or disable specific locales. Adding a new locale here requires adding it to payload.config.ts first.
   */
  activeLocales?:
    | {
        /**
         * e.g. en, id, zh — must match a code in payload.config.ts localization.locales
         */
        code: string;
        /**
         * e.g. English, Indonesian
         */
        label: string;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Locale used when none is detected. Must be in activeLocales.
   */
  defaultLocale?: string | null;
  /**
   * Read Accept-Language header and redirect visitors to their preferred locale.
   */
  autoDetect?: boolean | null;
  /**
   * Display the locale toggle in the header.
   */
  showSwitcher?: boolean | null;
  switcherPosition?: ('header' | 'footer') | null;
  /**
   * Add <link rel="alternate" hreflang="..."> tags to every page for multilanguage SEO.
   */
  hreflangEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Full-stack performance optimization. All toggles take effect immediately on save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance-settings".
 */
export interface PerformanceSetting {
  id: number;
  /**
   * Master switch. Disabling this no-ops all runtime features instantly.
   */
  pluginEnabled?: boolean | null;
  /**
   * Removes unoptimized: true in production. Requires sharp. Apply via withPerformance in next.config.ts.
   */
  imageOptimizationEnabled?: boolean | null;
  /**
   * Formats Next.js will generate. AVIF gives better compression but slower encoding.
   */
  imageFormats?: ('webp' | 'avif')[] | null;
  /**
   * Breakpoints used when generating responsive image srcsets.
   */
  imageDeviceSizes?: string | null;
  /**
   * Replaces no-store with no-cache + s-maxage for proxy caching. Apply via withPerformance.
   */
  cacheHeadersEnabled?: boolean | null;
  /**
   * s-maxage value. nginx/CDN serves cached HTML for this many seconds before revalidating.
   */
  htmlCacheTtl?: number | null;
  /**
   * How long the proxy serves stale content while fetching fresh in the background.
   */
  staleWhileRevalidate?: number | null;
  /**
   * Wraps data-heavy blocks in <Suspense> for streaming HTML delivery.
   */
  streamingEnabled?: boolean | null;
  /**
   * Number of animated grey bars shown while a streamed block loads.
   */
  skeletonRows?: number | null;
  /**
   * Caches page/navigation Payload queries across requests using unstable_cache.
   */
  queryCacheEnabled?: boolean | null;
  /**
   * How long page queries are cached before Payload is re-queried.
   */
  queryCacheTtl?: number | null;
  /**
   * Prefix for cache tags. Used with revalidateTag() for instant invalidation on content save.
   */
  queryCacheTags?: string | null;
  /**
   * Adds index: true to slug/updatedAt/locale/_status fields at config-build time. Requires restart.
   */
  sqliteIndexesEnabled?: boolean | null;
  /**
   * Collection slugs that receive auto-indexes.
   */
  indexedCollections?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  menuItems?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        megaMenu?: T;
        megaMenuStyle?: T;
        columns?:
          | T
          | {
              columnTitle?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
            };
        featured?:
          | T
          | {
              title?: T;
              description?: T;
              url?: T;
              cta?: T;
              image?: T;
            };
        id?: T;
      };
  ctaLabel?: T;
  ctaUrl?: T;
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  footerCopyrightMenu?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  ogImage?: T;
  maintenanceMode?: T;
  maintenanceTitle?: T;
  maintenanceMessage?: T;
  maintenanceStatusLabel?: T;
  maintenanceEstimate?: T;
  fromName?: T;
  fromEmail?: T;
  adminNotificationEmail?: T;
  smtpEnabled?: T;
  smtpHost?: T;
  smtpPort?: T;
  smtpSecure?: T;
  smtpUser?: T;
  smtpPassword?: T;
  accessControl?:
    | T
    | {
        collection?: T;
        canRead?: T;
        canCreate?: T;
        canUpdate?: T;
        canDelete?: T;
        id?: T;
      };
  googleAnalyticsId?: T;
  stripeEnabled?: T;
  loginMaxAttempts?: T;
  loginLockoutMinutes?: T;
  requireTwoFactor?: T;
  ipFilterEnabled?: T;
  ipBlocklist?:
    | T
    | {
        ip?: T;
        reason?: T;
        id?: T;
      };
  ipAllowlist?:
    | T
    | {
        ip?: T;
        id?: T;
      };
  apiRateLimitEnabled?: T;
  apiRateLimitMax?: T;
  cspEnabled?: T;
  cspReportOnly?: T;
  hstsEnabled?: T;
  canonicalDomain?: T;
  robotsDisallow?:
    | T
    | {
        path?: T;
        id?: T;
      };
  crawlDelay?: T;
  llmsTxtEnabled?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  siteName?: T;
  siteTagline?: T;
  logo?: T;
  favicon?: T;
  colorPreset?: T;
  colorScheme?: T;
  primaryColor?: T;
  secondaryColor?: T;
  bgColor?: T;
  surfaceColor?: T;
  textColor?: T;
  mutedColor?: T;
  borderColor?: T;
  testimonialsBg?: T;
  presetPreviewNote?: T;
  headingFont?: T;
  bodyFont?: T;
  footerDescription?: T;
  footerCopyright?: T;
  getStartedTitle?: T;
  getStartedDesc?: T;
  getStartedButtonLabel?: T;
  getStartedButtonUrl?: T;
  twitter?: T;
  facebook?: T;
  instagram?: T;
  linkedin?: T;
  github?: T;
  customCSS?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-settings_select".
 */
export interface ChatbotSettingsSelect<T extends boolean = true> {
  active?: T;
  botName?: T;
  greetingMessage?: T;
  defaultWhatsappUrl?: T;
  contactFormTitle?: T;
  notifyEmail?: T;
  nodes?:
    | T
    | {
        label?: T;
        answer?: T;
        showContactForm?: T;
        showWhatsapp?: T;
        whatsappUrl?: T;
        children?:
          | T
          | {
              label?: T;
              answer?: T;
              showContactForm?: T;
              showWhatsapp?: T;
              whatsappUrl?: T;
              subChildren?:
                | T
                | {
                    label?: T;
                    answer?: T;
                    showContactForm?: T;
                    showWhatsapp?: T;
                    whatsappUrl?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  showOnAllPages?: T;
  pageWhitelist?:
    | T
    | {
        path?: T;
        id?: T;
      };
  availabilityEnabled?: T;
  availabilityStart?: T;
  availabilityEnd?: T;
  availabilityMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "language-settings_select".
 */
export interface LanguageSettingsSelect<T extends boolean = true> {
  activeLocales?:
    | T
    | {
        code?: T;
        label?: T;
        enabled?: T;
        id?: T;
      };
  defaultLocale?: T;
  autoDetect?: T;
  showSwitcher?: T;
  switcherPosition?: T;
  hreflangEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance-settings_select".
 */
export interface PerformanceSettingsSelect<T extends boolean = true> {
  pluginEnabled?: T;
  imageOptimizationEnabled?: T;
  imageFormats?: T;
  imageDeviceSizes?: T;
  cacheHeadersEnabled?: T;
  htmlCacheTtl?: T;
  staleWhileRevalidate?: T;
  streamingEnabled?: T;
  skeletonRows?: T;
  queryCacheEnabled?: T;
  queryCacheTtl?: T;
  queryCacheTags?: T;
  sqliteIndexesEnabled?: T;
  indexedCollections?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}